export const GO_DATA_DEFAULT_FIELDS = [
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "id",
        label: "Id",
    },
    {
        optionSetValue: false,
        options: [],
        unique: true,
        mandatory: true,
        name: "visualId",
        label: "case or contact ID",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: true,
        name: "firstName",
        label: "First Name",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "middleName",
        label: "Middle Name",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "lastName",
        label: "Last Name",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: true,
        name: "name",
        label: "Name",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: true,
        name: "date",
        label: "Date",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "description",
        label: "Description",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "age.years",
        label: "Age - Years",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "age.months",
        label: "Age - Months",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dob",
        label: "Date of Birth",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "gender",
        label: "Gender",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "pregnancyStatus",
        label: "Pregnancy Status",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "occupation",
        label: "Occupation",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "riskLevel",
        label: "Risk Level",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "riskReason",
        label: "Risk Reason",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: true,
        name: "dateOfReporting",
        label: "Date of reporting",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "isDateOfReportingApproximate",
        label: "Date of reporting approximate",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "responsibleUserId",
        label: "Assigned User",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "followUpTeamId",
        label: "Follow-up assigned team",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "followUp.status",
        label: "Follow-up final status",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "vaccinesReceived.vaccine",
        label: "Vaccine",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "vaccinesReceived.date",
        label: "Vaccine date",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "vaccinesReceived.status",
        label: "Vaccine status",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "documents.type",
        label: "Document type",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "documents.number",
        label: "Document number",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: true,
        name: "addresses.typeId",
        label: "Address type",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "addresses.date",
        label: "Address date",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "addresses.phoneNumber",
        label: "Phone number",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "addresses.emailAddress",
        label: "Email address",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: true,
        name: "addresses.locationId",
        label: "Location",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "addresses.city",
        label: "City",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "addresses.addressLine1",
        label: "Address",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "addresses.postalCode",
        label: "Postal code",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "addresses.geoLocationAccurate",
        label: "Coordinates are accurate",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: true,
        name: "classification",
        label: "Case classification",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dateOfOnset",
        label: "Date of onset",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "isDateOfOnsetApproximate",
        label: "Date of onset approximate",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dateBecomeCase",
        label: "Date of becoming a case",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dateOfInfection",
        label: "Date of infection",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "outcomeId",
        label: "Outcome",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dateOfOutcome",
        label: "Date of outcome",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "transferRefused",
        label: "Refused transfer to treatment unit	",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dateRanges.typeId",
        label: "Hospitalization/isolation type",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dateRanges.centerName",
        label: "Centre Name",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dateRanges.locationId",
        label: "Location of hospital/facility",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dateRanges.comments",
        label: "Comments",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dateRanges.startDate",
        label: "From (Date)",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dateRanges.endDate",
        label: "To (Date)",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dateOfBurial",
        label: "Date of Burial",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "burialPlaceName",
        label: "Burial Place Name",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "burialLocationId",
        label: "Place of Burial",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "safeBurial",
        label: "Was burial performed safely?",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: true,
        name: "dateOfFirstContact",
        label: "Date of first contact",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "dateOfLastContact",
        label: "Date of last contact",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "contactDateEstimated",
        label: "Is contact date estimated?",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "certaintyLevelId",
        label: "Certainty level",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "exposureTypeId",
        label: "Exposure type",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "exposureFrequencyId",
        label: "Exposure frequency",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "exposureDurationId",
        label: "Exposure duration",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "clusterId",
        label: "Cluster",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "socialRelationshipTypeId",
        label: "Context of exposure",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "socialRelationshipDetail",
        label: "Relationship",
    },
    {
        optionSetValue: false,
        options: [],
        unique: false,
        mandatory: false,
        name: "comment",
        label: "Comments",
    },

    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "sampleIdentifier",
        label: "Sample Lab ID",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "dateSampleTaken",
        label: "Date sample taken",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "dateSampleDelivered",
        label: "Date sample delivered to lab",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "dateTesting",
        label: "Date sample tested",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "dateOfResult",
        label: "Date of the result",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "labName",
        label: "Lab name",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "sampleType",
        label: "Sample type",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "testType",
        label: "Test type",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "result",
        label: "Result",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "status",
        label: "Status",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "testedFor",
        label: "Tested for",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "quantitativeResult",
        label: "Quantitative result",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "notes",
        label: "Notes",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "sequence.hasSequence",
        label: "Has variant/strain?",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "sequence.dateSampleSent",
        label: "Date sample sent for determining variant/strain",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "sequence.labId",
        label: "Variant/strain Lab Name",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "sequence.dateResult",
        label: "Variant/strain result date",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "sequence.resultId",
        label: "Variant/strain result",
    },
    {
        optionSetValue: false,
        options: [],
        mandatory: false,
        name: "sequence.noSequenceReason",
        label: "Reason:",
    },
];
export const DATE_TIME_FORMAT = "YYYY-MM-DD HH:mm:ss";
export const DATE_FORMAT = "YYYY-MM-DD";
