import { Option } from "./interfaces";

export const DATE_TIME_FORMAT = "YYYY-MM-DD HH:mm:ss";
export const DATE_FORMAT = "YYYY-MM-DD";
export const GO_DATA_PERSON_FIELDS: Option[] = [
    {
        value: "visualId",
        label: "case ID or contact ID or event ID",
        mandatory: true,
        multiple: false,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: true,
        valueType: "TEXT",
    },
    {
        value: "firstName",
        label: "First Name",
        mandatory: true,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "middleName",
        label: "Middle Name",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "lastName",
        label: "Last Name",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "age.months",
        label: "Age - Months",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "integer",
    },
    {
        value: "age.years",
        label: "Age - Years",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "integer",
    },
    {
        value: "dob",
        label: "Date of Birth",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "gender",
        label: "Gender",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                value: "Female",
                label: "Female",
                id: "LNG_REFERENCE_DATA_CATEGORY_GENDER_FEMALE",
            },
            {
                value: "Male",
                label: "Male",
                id: "LNG_REFERENCE_DATA_CATEGORY_GENDER_MALE",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "pregnancyStatus",
        label: "Pregnancy Status",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                value: "None",
                label: "None",
                id: "LNG_REFERENCE_DATA_CATEGORY_PREGNANCY_STATUS_NONE",
            },
            {
                value: "No - not pregnant",
                label: "No - not pregnant",
                id: "LNG_REFERENCE_DATA_CATEGORY_PREGNANCY_STATUS_NOT_PREGNANT",
            },
            {
                value: "Yes - first trimester",
                label: "Yes - first trimester",
                id: "LNG_REFERENCE_DATA_CATEGORY_PREGNANCY_STATUS_YES_FIRST_TRIMESTER",
            },
            {
                value: "Yes - second trimester",
                label: "Yes - second trimester",
                id: "LNG_REFERENCE_DATA_CATEGORY_PREGNANCY_STATUS_YES_SECOND_TRIMESTER",
            },
            {
                value: "Yes - third trimester",
                label: "Yes - third trimester",
                id: "LNG_REFERENCE_DATA_CATEGORY_PREGNANCY_STATUS_YES_THIRD_TRIMESTER",
            },
            {
                value: "Yes - trimester unknown",
                label: "Yes - trimester unknown",
                id: "LNG_REFERENCE_DATA_CATEGORY_PREGNANCY_STATUS_YES_TRIMESTER_UNKNOWN",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "occupation",
        label: "Occupation",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                value: "Butcher",
                label: "Butcher",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_BUTCHER",
            },
            {
                value: "Child",
                label: "Child",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_CHILD",
            },
            {
                value: "Civil servant",
                label: "Civil servant",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_CIVIL_SERVANT",
            },
            {
                value: "Farmer",
                label: "Farmer",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_FARMER",
            },
            {
                value: "Forestry",
                label: "Forestry",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_FORESTRY",
            },
            {
                value: "Health care worker",
                label: "Health care worker",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_HEALTH_CARE_WORKER",
            },
            {
                value: "Health laboratory worker",
                label: "Health laboratory worker",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_HEALTH_LABORATORY_WORKER",
            },
            {
                value: "Hunter",
                label: "Hunter",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_HUNTER",
            },
            {
                value: "Mining",
                label: "Mining",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_MINING",
            },
            {
                value: "Other",
                label: "Other",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_OTHER",
            },
            {
                value: "Religious leader",
                label: "Religious leader",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_RELIGIOUS_LEADER",
            },
            {
                value: "Student",
                label: "Student",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_STUDENT",
            },
            {
                value: "Taxi driver",
                label: "Taxi driver",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_TAXI_DRIVER",
            },
            {
                value: "Teacher",
                label: "Teacher",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_TEACHER",
            },
            {
                value: "Traditional healer",
                label: "Traditional healer",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_TRADITIONAL_HEALER",
            },
            {
                value: "Unknown",
                label: "Unknown",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_UNKNOWN",
            },
            {
                value: "Working with animals",
                label: "Working with animals",
                id: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_WORKING_WITH_ANIMALS",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "riskLevel",
        label: "Risk Level",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                value: "1 - Low",
                label: "1 - Low",
                id: "LNG_REFERENCE_DATA_CATEGORY_RISK_LEVEL_1_LOW",
            },
            {
                value: "2 - Medium",
                label: "2 - Medium",
                id: "LNG_REFERENCE_DATA_CATEGORY_RISK_LEVEL_2_MEDIUM",
            },
            {
                value: "3 - High",
                label: "3 - High",
                id: "LNG_REFERENCE_DATA_CATEGORY_RISK_LEVEL_3_HIGH",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "riskReason",
        label: "Risk Reason",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateOfReporting",
        label: "Date of reporting",
        mandatory: true,
        multiple: false,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "isDateOfReportingApproximate",
        label: "Date of reporting approximate",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "BOOLEAN",
    },
    {
        value: "responsibleUserId",
        label: "Assigned User",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "followUpTeamId",
        label: "Follow-up assigned team",
        mandatory: false,
        multiple: false,
        entity: "CONTACT",
        valueType: "TEXT",
    },
    {
        value: "followUp.status",
        label: "Follow-up final status",
        mandatory: false,
        multiple: false,
        availableOptions: [
            {
                value: "Died",
                label: "Died",
                id: "LNG_REFERENCE_DATA_CONTACT_FINAL_FOLLOW_UP_STATUS_TYPE_DIED",
            },
            {
                value: "Follow-up completed",
                label: "Follow-up completed",
                id: "LNG_REFERENCE_DATA_CONTACT_FINAL_FOLLOW_UP_STATUS_TYPE_FOLLOW_UP_COMPLETED",
            },
            {
                value: "Lost to follow-up",
                label: "Lost to follow-up",
                id: "LNG_REFERENCE_DATA_CONTACT_FINAL_FOLLOW_UP_STATUS_TYPE_LOST_TO_FOLLOW_UP",
            },
            {
                value: "Never ill/not a case",
                label: "Never ill/not a case",
                id: "LNG_REFERENCE_DATA_CONTACT_FINAL_FOLLOW_UP_STATUS_TYPE_NEVER_ILL_NOT_A_CASE",
            },
            {
                value: "Under follow-up",
                label: "Under follow-up",
                id: "LNG_REFERENCE_DATA_CONTACT_FINAL_FOLLOW_UP_STATUS_TYPE_UNDER_FOLLOW_UP",
            },
        ],
        optionSetValue: true,
        entity: "CONTACT",
        valueType: "TEXT",
    },
    {
        value: "vaccinesReceived[0].vaccine",
        label: "Vaccine",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "vaccinesReceived[0].date",
        label: "Vaccine date",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "vaccinesReceived[0].status",
        label: "Vaccine status",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                value: "Not vaccinated",
                label: "Not vaccinated",
                id: "LNG_REFERENCE_DATA_CATEGORY_VACCINE_STATUS_NOT_VACCINATED",
            },
            {
                value: "Vaccinated",
                label: "Vaccinated",
                id: "LNG_REFERENCE_DATA_CATEGORY_VACCINE_STATUS_VACCINATED",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "documents[0].type",
        label: "Document type",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                value: "Archived ID",
                label: "Archived ID",
                id: "LNG_REFERENCE_DATA_CATEGORY_DOCUMENT_TYPE_ARCHIVED_ID",
            },
            {
                value: "External case ID",
                label: "External case ID",
                id: "LNG_REFERENCE_DATA_CATEGORY_DOCUMENT_TYPE_EXTERNAL_ID",
            },
            {
                value: "National ID card",
                label: "National ID card",
                id: "LNG_REFERENCE_DATA_CATEGORY_DOCUMENT_TYPE_NATIONAL_ID_CARD",
            },
            {
                value: "Other",
                label: "Other",
                id: "LNG_REFERENCE_DATA_CATEGORY_DOCUMENT_TYPE_OTHER",
            },
            {
                value: "Passport",
                label: "Passport",
                id: "LNG_REFERENCE_DATA_CATEGORY_DOCUMENT_TYPE_PASSPORT",
            },
            {
                value: "Vaccination card",
                label: "Vaccination card",
                id: "LNG_REFERENCE_DATA_CATEGORY_DOCUMENT_TYPE_VACCINATION_CARD",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "documents[0].number",
        label: "Document number",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].typeId",
        label: "Location Type",
        mandatory: true,
        multiple: true,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [
            {
                value: "Other",
                label: "Other",
                id: "LNG_REFERENCE_DATA_CATEGORY_ADDRESS_TYPE_OTHER",
            },
            {
                value: "Previous address",
                label: "Previous address",
                id: "LNG_REFERENCE_DATA_CATEGORY_ADDRESS_TYPE_PREVIOUS_USUAL_PLACE_OF_RESIDENCE",
            },
            {
                value: "Current address",
                label: "Current address",
                id: "LNG_REFERENCE_DATA_CATEGORY_ADDRESS_TYPE_USUAL_PLACE_OF_RESIDENCE",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].date",
        label: "Date",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "addresses[0].phoneNumber",
        label: "Phone number",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].emailAddress",
        label: "Email address",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].locationId",
        label: "Location",
        mandatory: true,
        multiple: true,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        isOrgUnit: true,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].city",
        label: "City",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].addressLine1",
        label: "Address",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].postalCode",
        label: "Postal code",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].geoLocationAccurate",
        label: "Coordinates are accurate",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "BOOLEAN",
    },
];
export const GO_DATA_EVENTS_FIELDS: Option[] = [
    {
        value: "name",
        label: "Name",
        mandatory: true,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "date",
        label: "Date",
        mandatory: true,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "endDate",
        label: "End date",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "eventCategory",
        label: "Category",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "description",
        label: "Description",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
];
export const GO_DATA_EPIDEMIOLOGY_FIELDS: Option[] = [
    {
        value: "classification",
        label: "Case classification",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [
            {
                value: "Confirmed",
                label: "Confirmed",
                id: "LNG_REFERENCE_DATA_CATEGORY_CASE_CLASSIFICATION_CONFIRMED",
            },
            {
                value: "Not a case (discarded)",
                label: "Not a case (discarded)",
                id: "LNG_REFERENCE_DATA_CATEGORY_CASE_CLASSIFICATION_NOT_A_CASE_DISCARDED",
            },
            {
                value: "Probable",
                label: "Probable",
                id: "LNG_REFERENCE_DATA_CATEGORY_CASE_CLASSIFICATION_PROBABLE",
            },
            {
                value: "Suspect",
                label: "Suspect",
                id: "LNG_REFERENCE_DATA_CATEGORY_CASE_CLASSIFICATION_SUSPECT",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateOfOnset",
        label: "Date of onset",
        mandatory: true,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "isDateOfOnsetApproximate",
        label: "Date of onset approximate",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "BOOLEAN",
    },
    {
        value: "dateBecomeCase",
        label: "Date of becoming a case",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "dateOfInfection",
        label: "Date of infection",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "outcomeId",
        label: "Outcome",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [
            {
                value: "Alive",
                label: "Alive",
                id: "LNG_REFERENCE_DATA_CATEGORY_OUTCOME_ALIVE",
            },
            {
                value: "Deceased",
                label: "Deceased",
                id: "LNG_REFERENCE_DATA_CATEGORY_OUTCOME_DECEASED",
            },
            {
                value: "Recovered",
                label: "Recovered",
                id: "LNG_REFERENCE_DATA_CATEGORY_OUTCOME_RECOVERED",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateOfOutcome",
        label: "Date of outcome",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "transferRefused",
        label: "Refused transfer to treatment unit",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "BOOLEAN",
    },
    {
        value: "dateRanges[0].typeId",
        label: "Hospitalization/isolation type",
        mandatory: false,
        multiple: true,
        entity: "CASE",
        availableOptions: [
            {
                value: "A&E visit",
                label: "A&E visit",
                id: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_A_E_VISIT",
            },
            {
                value: "Hospitalization",
                label: "Hospitalization",
                id: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_HOSPITALIZATION",
            },
            {
                value: "Hospitalization for other medical conditions",
                label: "Hospitalization for other medical conditions",
                id: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_HOSPITALIZATION_FOR_OTHER_MEDICAL_CONDITIONS",
            },
            {
                value: "ICU Admission",
                label: "ICU Admission",
                id: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_ICU_ADMISSION",
            },
            {
                value: "Isolation",
                label: "Isolation",
                id: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_ISOLATION",
            },
            {
                value: "Other",
                label: "Other",
                id: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_OTHER",
            },
            {
                value: "Outpatient visit",
                label: "Outpatient visit",
                id: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_OUTPATIENT_VISIT",
            },
            {
                value: "Primary health care PHC (GP, etc) visit",
                label: "Primary health care PHC (GP, etc) visit",
                id: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_PRIMARY_HEALTH_CARE_PHC_GP_ETC_VISIT",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateRanges[0].centerName",
        label: "Centre Name",
        mandatory: false,
        multiple: true,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateRanges[0].locationId",
        label: "Location of hospital/facility",
        mandatory: false,
        multiple: true,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateRanges[0].comments",
        label: "Comments",
        mandatory: false,
        multiple: true,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateRanges[0].startDate",
        label: "From (Date)",
        mandatory: false,
        multiple: true,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "dateRanges[0].endDate",
        label: "To (Date)",
        mandatory: false,
        multiple: true,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "dateOfBurial",
        label: "Date of Burial",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "burialPlaceName",
        label: "Burial Place Name",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "burialLocationId",
        label: "Place of Burial",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "safeBurial",
        label: "Was burial performed safely?",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "BOOLEAN",
    },
];
export const GO_DATA_LAB_FIELDS: Option[] = [];
