import { Option } from "./interfaces";

export const DATE_TIME_FORMAT = "YYYY-MM-DD HH:mm:ss";
export const DATE_FORMAT = "YYYY-MM-DD";
export const GO_DATA_PERSON_FIELDS: Option[] = [
    {
        value: "visualId",
        mandatory: true,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: true,
        valueType: "TEXT",
        label: "case ID",
    },
    {
        value: "visualId",
        mandatory: true,
        multiple: false,
        entity: "CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: true,
        valueType: "TEXT",
        label: "contact ID",
    },
    {
        value: "visualId",
        mandatory: true,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: true,
        valueType: "TEXT",
        label: "event ID",
    },
    {
        value: "firstName",
        label: "First Name",
        mandatory: true,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "middleName",
        label: "Middle Name",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "lastName",
        label: "Last Name",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "age.months",
        label: "Age - Months",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "INTEGER",
    },
    {
        value: "age.years",
        label: "Age - Years",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "INTEGER",
    },
    {
        value: "dob",
        label: "Date of Birth",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "gender",
        label: "Gender",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                id: "Female",
                label: "Female",
                value: "LNG_REFERENCE_DATA_CATEGORY_GENDER_FEMALE",
            },
            {
                id: "Male",
                label: "Male",
                value: "LNG_REFERENCE_DATA_CATEGORY_GENDER_MALE",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "pregnancyStatus",
        label: "Pregnancy Status",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                id: "None",
                label: "None",
                value: "LNG_REFERENCE_DATA_CATEGORY_PREGNANCY_STATUS_NONE",
            },
            {
                id: "No - not pregnant",
                label: "No - not pregnant",
                value: "LNG_REFERENCE_DATA_CATEGORY_PREGNANCY_STATUS_NOT_PREGNANT",
            },
            {
                id: "Yes - first trimester",
                label: "Yes - first trimester",
                value: "LNG_REFERENCE_DATA_CATEGORY_PREGNANCY_STATUS_YES_FIRST_TRIMESTER",
            },
            {
                id: "Yes - second trimester",
                label: "Yes - second trimester",
                value: "LNG_REFERENCE_DATA_CATEGORY_PREGNANCY_STATUS_YES_SECOND_TRIMESTER",
            },
            {
                id: "Yes - third trimester",
                label: "Yes - third trimester",
                value: "LNG_REFERENCE_DATA_CATEGORY_PREGNANCY_STATUS_YES_THIRD_TRIMESTER",
            },
            {
                id: "Yes - trimester unknown",
                label: "Yes - trimester unknown",
                value: "LNG_REFERENCE_DATA_CATEGORY_PREGNANCY_STATUS_YES_TRIMESTER_UNKNOWN",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "occupation",
        label: "Occupation",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                id: "Butcher",
                label: "Butcher",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_BUTCHER",
            },
            {
                id: "Child",
                label: "Child",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_CHILD",
            },
            {
                id: "Civil servant",
                label: "Civil servant",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_CIVIL_SERVANT",
            },
            {
                id: "Farmer",
                label: "Farmer",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_FARMER",
            },
            {
                id: "Forestry",
                label: "Forestry",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_FORESTRY",
            },
            {
                id: "Health care worker",
                label: "Health care worker",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_HEALTH_CARE_WORKER",
            },
            {
                id: "Health laboratory worker",
                label: "Health laboratory worker",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_HEALTH_LABORATORY_WORKER",
            },
            {
                id: "Hunter",
                label: "Hunter",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_HUNTER",
            },
            {
                id: "Mining",
                label: "Mining",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_MINING",
            },
            {
                id: "Other",
                label: "Other",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_OTHER",
            },
            {
                id: "Religious leader",
                label: "Religious leader",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_RELIGIOUS_LEADER",
            },
            {
                id: "Student",
                label: "Student",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_STUDENT",
            },
            {
                id: "Taxi driver",
                label: "Taxi driver",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_TAXI_DRIVER",
            },
            {
                id: "Teacher",
                label: "Teacher",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_TEACHER",
            },
            {
                id: "Traditional healer",
                label: "Traditional healer",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_TRADITIONAL_HEALER",
            },
            {
                id: "Unknown",
                label: "Unknown",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_UNKNOWN",
            },
            {
                id: "Working with animals",
                label: "Working with animals",
                value: "LNG_REFERENCE_DATA_CATEGORY_OCCUPATION_WORKING_WITH_ANIMALS",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "riskLevel",
        label: "Risk Level",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                id: "1 - Low",
                label: "1 - Low",
                value: "LNG_REFERENCE_DATA_CATEGORY_RISK_LEVEL_1_LOW",
            },
            {
                id: "2 - Medium",
                label: "2 - Medium",
                value: "LNG_REFERENCE_DATA_CATEGORY_RISK_LEVEL_2_MEDIUM",
            },
            {
                id: "3 - High",
                label: "3 - High",
                value: "LNG_REFERENCE_DATA_CATEGORY_RISK_LEVEL_3_HIGH",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "riskReason",
        label: "Risk Reason",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateOfReporting",
        label: "Date of reporting",
        mandatory: true,
        multiple: false,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "isDateOfReportingApproximate",
        label: "Date of reporting approximate",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "BOOLEAN",
    },
    {
        value: "responsibleUserId",
        label: "Assigned User",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT/EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "followUpTeamId",
        label: "Follow-up assigned team",
        mandatory: false,
        multiple: false,
        entity: "CONTACT",
        valueType: "TEXT",
    },
    {
        value: "followUp.status",
        label: "Follow-up final status",
        mandatory: false,
        multiple: false,
        availableOptions: [
            {
                id: "Died",
                label: "Died",
                value: "LNG_REFERENCE_DATA_CONTACT_FINAL_FOLLOW_UP_STATUS_TYPE_DIED",
            },
            {
                id: "Follow-up completed",
                label: "Follow-up completed",
                value: "LNG_REFERENCE_DATA_CONTACT_FINAL_FOLLOW_UP_STATUS_TYPE_FOLLOW_UP_COMPLETED",
            },
            {
                id: "Lost to follow-up",
                label: "Lost to follow-up",
                value: "LNG_REFERENCE_DATA_CONTACT_FINAL_FOLLOW_UP_STATUS_TYPE_LOST_TO_FOLLOW_UP",
            },
            {
                id: "Never ill/not a case",
                label: "Never ill/not a case",
                value: "LNG_REFERENCE_DATA_CONTACT_FINAL_FOLLOW_UP_STATUS_TYPE_NEVER_ILL_NOT_A_CASE",
            },
            {
                id: "Under follow-up",
                label: "Under follow-up",
                value: "LNG_REFERENCE_DATA_CONTACT_FINAL_FOLLOW_UP_STATUS_TYPE_UNDER_FOLLOW_UP",
            },
        ],
        optionSetValue: true,
        entity: "CONTACT",
        valueType: "TEXT",
    },
    {
        value: "vaccinesReceived[0].vaccine",
        label: "Vaccine",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "vaccinesReceived[0].date",
        label: "Vaccine date",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "vaccinesReceived[0].status",
        label: "Vaccine status",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                id: "Not vaccinated",
                label: "Not vaccinated",
                value: "LNG_REFERENCE_DATA_CATEGORY_VACCINE_STATUS_NOT_VACCINATED",
            },
            {
                id: "Vaccinated",
                label: "Vaccinated",
                value: "LNG_REFERENCE_DATA_CATEGORY_VACCINE_STATUS_VACCINATED",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "documents[0].type",
        label: "Document type",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                id: "Archived ID",
                label: "Archived ID",
                value: "LNG_REFERENCE_DATA_CATEGORY_DOCUMENT_TYPE_ARCHIVED_ID",
            },
            {
                id: "External case ID",
                label: "External case ID",
                value: "LNG_REFERENCE_DATA_CATEGORY_DOCUMENT_TYPE_EXTERNAL_ID",
            },
            {
                id: "National ID card",
                label: "National ID card",
                value: "LNG_REFERENCE_DATA_CATEGORY_DOCUMENT_TYPE_NATIONAL_ID_CARD",
            },
            {
                id: "Other",
                label: "Other",
                value: "LNG_REFERENCE_DATA_CATEGORY_DOCUMENT_TYPE_OTHER",
            },
            {
                id: "Passport",
                label: "Passport",
                value: "LNG_REFERENCE_DATA_CATEGORY_DOCUMENT_TYPE_PASSPORT",
            },
            {
                id: "Vaccination card",
                label: "Vaccination card",
                value: "LNG_REFERENCE_DATA_CATEGORY_DOCUMENT_TYPE_VACCINATION_CARD",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "documents[0].number",
        label: "Document number",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].typeId",
        label: "Location Type",
        mandatory: true,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                id: "Other",
                label: "Other",
                value: "LNG_REFERENCE_DATA_CATEGORY_ADDRESS_TYPE_OTHER",
            },
            {
                id: "Previous address",
                label: "Previous address",
                value: "LNG_REFERENCE_DATA_CATEGORY_ADDRESS_TYPE_PREVIOUS_USUAL_PLACE_OF_RESIDENCE",
            },
            {
                id: "Current address",
                label: "Current address",
                value: "LNG_REFERENCE_DATA_CATEGORY_ADDRESS_TYPE_USUAL_PLACE_OF_RESIDENCE",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].date",
        label: "Date",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "addresses[0].phoneNumber",
        label: "Phone number",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].emailAddress",
        label: "Email address",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].locationId",
        label: "Location",
        mandatory: true,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        isOrgUnit: true,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].city",
        label: "City",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].addressLine1",
        label: "Address",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].postalCode",
        label: "Postal code",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "addresses[0].geoLocationAccurate",
        label: "Coordinates are accurate",
        mandatory: false,
        multiple: true,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "BOOLEAN",
    },
];
export const GO_DATA_EVENTS_FIELDS: Option[] = [
    {
        value: "name",
        label: "Name",
        mandatory: true,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "date",
        label: "Date",
        mandatory: true,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "endDate",
        label: "End date",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "eventCategory",
        label: "Category",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "description",
        label: "Description",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "address.date",
        label: "Date",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "address.phoneNumber",
        label: "Phone number",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "address.emailAddress",
        label: "Email address",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "address.locationId",
        label: "Location",
        mandatory: true,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        isOrgUnit: true,
        valueType: "TEXT",
    },
    {
        value: "address.city",
        label: "City",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "address.addressLine1",
        label: "Address",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "address.postalCode",
        label: "Postal code",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "address.geoLocationAccurate",
        label: "Coordinates are accurate",
        mandatory: false,
        multiple: false,
        entity: "EVENT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "BOOLEAN",
    },
];
export const GO_DATA_EPIDEMIOLOGY_FIELDS: Option[] = [
    {
        value: "classification",
        label: "Case classification",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [
            {
                id: "Confirmed",
                label: "Confirmed",
                value: "LNG_REFERENCE_DATA_CATEGORY_CASE_CLASSIFICATION_CONFIRMED",
            },
            {
                id: "Not a case (discarded)",
                label: "Not a case (discarded)",
                value: "LNG_REFERENCE_DATA_CATEGORY_CASE_CLASSIFICATION_NOT_A_CASE_DISCARDED",
            },
            {
                id: "Probable",
                label: "Probable",
                value: "LNG_REFERENCE_DATA_CATEGORY_CASE_CLASSIFICATION_PROBABLE",
            },
            {
                id: "Suspect",
                label: "Suspect",
                value: "LNG_REFERENCE_DATA_CATEGORY_CASE_CLASSIFICATION_SUSPECT",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateOfOnset",
        label: "Date of onset",
        mandatory: true,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "isDateOfOnsetApproximate",
        label: "Date of onset approximate",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "BOOLEAN",
    },
    {
        value: "dateBecomeCase",
        label: "Date of becoming a case",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "dateOfInfection",
        label: "Date of infection",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "outcomeId",
        label: "Outcome",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [
            {
                id: "Alive",
                label: "Alive",
                value: "LNG_REFERENCE_DATA_CATEGORY_OUTCOME_ALIVE",
            },
            {
                id: "Deceased",
                label: "Deceased",
                value: "LNG_REFERENCE_DATA_CATEGORY_OUTCOME_DECEASED",
            },
            {
                id: "Recovered",
                label: "Recovered",
                value: "LNG_REFERENCE_DATA_CATEGORY_OUTCOME_RECOVERED",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateOfOutcome",
        label: "Date of outcome",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "transferRefused",
        label: "Refused transfer to treatment unit",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "BOOLEAN",
    },
    {
        value: "dateRanges[0].typeId",
        label: "Hospitalization/isolation type",
        mandatory: false,
        multiple: true,
        entity: "CASE",
        availableOptions: [
            {
                id: "A&E visit",
                label: "A&E visit",
                value: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_A_E_VISIT",
            },
            {
                id: "Hospitalization",
                label: "Hospitalization",
                value: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_HOSPITALIZATION",
            },
            {
                id: "Hospitalization for other medical conditions",
                label: "Hospitalization for other medical conditions",
                value: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_HOSPITALIZATION_FOR_OTHER_MEDICAL_CONDITIONS",
            },
            {
                id: "ICU Admission",
                label: "ICU Admission",
                value: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_ICU_ADMISSION",
            },
            {
                id: "Isolation",
                label: "Isolation",
                value: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_ISOLATION",
            },
            {
                id: "Other",
                label: "Other",
                value: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_OTHER",
            },
            {
                id: "Outpatient visit",
                label: "Outpatient visit",
                value: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_OUTPATIENT_VISIT",
            },
            {
                id: "Primary health care PHC (GP, etc) visit",
                label: "Primary health care PHC (GP, etc) visit",
                value: "LNG_REFERENCE_DATA_CATEGORY_PERSON_DATE_TYPE_PRIMARY_HEALTH_CARE_PHC_GP_ETC_VISIT",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateRanges[0].centerName",
        label: "Centre Name",
        mandatory: false,
        multiple: true,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateRanges[0].locationId",
        label: "Location of hospital/facility",
        mandatory: false,
        multiple: true,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateRanges[0].comments",
        label: "Comments",
        mandatory: false,
        multiple: true,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "dateRanges[0].startDate",
        label: "From (Date)",
        mandatory: false,
        multiple: true,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "dateRanges[0].endDate",
        label: "To (Date)",
        mandatory: false,
        multiple: true,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "dateOfBurial",
        label: "Date of Burial",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
    },
    {
        value: "burialPlaceName",
        label: "Burial Place Name",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "burialLocationId",
        label: "Place of Burial",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
    },
    {
        value: "safeBurial",
        label: "Was burial performed safely?",
        mandatory: false,
        multiple: false,
        entity: "CASE",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "BOOLEAN",
    },
];
export const GO_DATA_LAB_FIELDS: Option[] = [
    {
        value: "sampleIdentifier",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Sample Lab ID",
    },
    {
        value: "dateSampleTaken",
        mandatory: true,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
        label: "Date sample taken",
    },
    {
        value: "dateSampleDelivered",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
        label: "Date sample delivered to lab",
    },
    {
        value: "dateTesting",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
        label: "Date sample tested",
    },
    {
        value: "dateOfResult",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
        label: "Date of the result",
    },
    {
        value: "labName",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Lab name",
    },
    {
        value: "sampleType",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                label: "Blood",
                value: "blood",
            },
            {
                label: "Nasopharyngeal swab",
                value: "nasopharyngeal_swab",
            },
            {
                label: "CSF",
                value: "csf",
            },
            {
                label: "Skin biopsy",
                value: "skin_biopsy",
            },
            {
                label: "Sputum",
                value: "sputum",
            },
            {
                label: "Throat swab",
                value: "throat_swab",
            },
            {
                label: "Endotracheal aspirate",
                value: "endotracheal_aspirate",
            },
            {
                label: "Nasal swab",
                value: "nasal_swab",
            },
            {
                label: "Faeces",
                value: "faeces",
            },
            {
                label: "Other (specify in Notes field)",
                value: "other",
            },
            {
                label: "Pleural fluid",
                value: "pleural_fluid",
            },
            {
                label: "Serum",
                value: "serum",
            },
            {
                label: "Urine",
                value: "urine",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
        label: "Sample type",
    },
    {
        value: "testType",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                label: "RT-PCR",
                value: "rt_pcr",
            },
            {
                label: "Whole genome sequencing",
                value: "whole_sequencing",
            },
            {
                label: "Partial genome sequencing",
                value: "partial_sequencing",
            },
            {
                label: "Serology (IgG, IgM, etc.)",
                value: "serology",
            },
            {
                label: "PCR",
                value: "pcr",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
        label: "Test type",
    },
    {
        value: "result",
        mandatory: true,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [
            {
                label: "Positive for targeted pathogen (if serology, enter titre in Quantitative result)",
                value: "positive",
            },
            {
                label: "Negative for targeted pathogen",
                value: "negative",
            },
            {
                label: "Inconclusive for targeted pathogen",
                value: "inconclusive",
            },
            {
                label: "Positive for other pathogens (specify in Notes field)",
                value: "positive_other",
            },
        ],
        optionSetValue: true,
        unique: false,
        valueType: "TEXT",
        label: "Result",
    },
    {
        value: "status",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Status",
    },
    {
        value: "testedFor",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Tested for",
    },
    {
        value: "quantitativeResult",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Quantitative result",
    },
    {
        value: "notes",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Notes",
    },
    {
        value: "sequence.hasSequence",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "BOOLEAN",
        label: "Has variant/strain?",
    },
    {
        value: "sequence.dateSampleSent",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
        label: "Date sample sent for determining variant/strain",
    },
    {
        value: "sequence.labId",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Variant/strain Lab Name",
    },
    {
        value: "sequence.dateResult",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
        label: "Variant/strain result date",
    },
    {
        value: "sequence.resultId",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Variant/strain result",
    },
    {
        value: "sequence.noSequenceReason",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Reason",
    },
];

export const GO_DATA_RELATIONSHIP_FIELDS: Option[] = [
    {
        value: "dateOfFirstContact",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
        label: "Date of first contact",
    },
    {
        value: "dateOfLastContact",
        mandatory: true,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "DATE",
        label: "Date of last contact",
    },
    {
        value: "contactDateEstimated",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Is contact date estimated?",
    },
    {
        value: "certaintyLevelId",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Certainty level",
    },
    {
        value: "exposureTypeId",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Exposure type",
    },
    {
        value: "exposureFrequencyId",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Exposure frequency",
    },
    {
        value: "exposureDurationId",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Exposure duration",
    },
    {
        value: "clusterId",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Cluster",
    },
    {
        value: "socialRelationshipTypeId",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Context of exposure",
    },
    {
        value: "socialRelationshipDetail",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Relationship",
    },
    {
        value: "comment",
        mandatory: false,
        multiple: false,
        entity: "CASE/CONTACT",
        availableOptions: [],
        optionSetValue: false,
        unique: false,
        valueType: "TEXT",
        label: "Comments",
    },
];
