import { TrackedEntityInstance } from "./interfaces";

export const data: {
    trackedEntityInstances: Array<Partial<TrackedEntityInstance>>;
} = {
    trackedEntityInstances: [
        {
            created: "2023-04-06T06:14:15.004",
            orgUnit: "a4gTh6i5VdH",
            createdAtClient: "2023-04-06T06:14:15.004",
            trackedEntityInstance: "VgzcxlyMAOR",
            lastUpdated: "2023-04-06T09:50:37.286",
            trackedEntityType: "KWN8FUfvO5G",
            lastUpdatedAtClient: "2023-04-06T06:14:15.004",
            inactive: false,
            deleted: false,
            featureType: "NONE",
            programOwners: [
                {
                    ownerOrgUnit: "a4gTh6i5VdH",
                    program: "o6TN8Sr45CZ",
                    trackedEntityInstance: "VgzcxlyMAOR",
                },
            ],
            enrollments: [
                {
                    storedBy: "Charles.Olupot",
                    created: "2023-04-06T06:14:16.259",
                    orgUnit: "a4gTh6i5VdH",
                    createdAtClient: "2023-04-06T06:14:16.265",
                    program: "o6TN8Sr45CZ",
                    trackedEntityInstance: "VgzcxlyMAOR",
                    enrollment: "ma8b1wyyDyv",
                    lastUpdated: "2023-04-06T06:14:16.266",
                    trackedEntityType: "KWN8FUfvO5G",
                    lastUpdatedAtClient: "2023-04-06T06:14:16.266",
                    orgUnitName: "1 Test OU",
                    enrollmentDate: "2023-04-06T00:00:00.000",
                    deleted: false,
                    incidentDate: "2023-04-06T00:00:00.000",
                    status: "ACTIVE",
                    notes: [],
                    relationships: [],
                    attributes: [],
                    events: [
                        {
                            storedBy: "Charles.Olupot",
                            dueDate: "2023-04-06T09:24:21.287",
                            program: "o6TN8Sr45CZ",
                            event: "cVIUI7buN5H",
                            programStage: "zKFHLSj6Wd1",
                            orgUnit: "a4gTh6i5VdH",
                            trackedEntityInstance: "VgzcxlyMAOR",
                            enrollment: "ma8b1wyyDyv",
                            enrollmentStatus: "ACTIVE",
                            status: "ACTIVE",
                            orgUnitName: "1 Test OU",
                            eventDate: "2023-04-06T00:00:00.000",
                            attributeCategoryOptions: "xYerKDKCefk",
                            lastUpdated: "2023-04-06T09:24:21.288",
                            created: "2023-04-06T06:15:37.001",
                            deleted: false,
                            attributeOptionCombo: "HllvX50cXC0",
                            dataValues: [
                                {
                                    lastUpdated: "2023-04-06T09:20:05.932",
                                    created: "2023-04-06T09:20:05.932",
                                    dataElement: "Iwiv0W39Yqq",
                                    value: "PCR",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-06T09:20:35.276",
                                    created: "2023-04-06T06:17:38.457",
                                    dataElement: "GzIo6aEN7Mc",
                                    value: "2023-04-06",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-06T09:24:21.286",
                                    created: "2023-04-06T09:20:03.631",
                                    dataElement: "Ju7cS1sUwcF",
                                    value: "L2024_0012",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-06T09:20:29.699",
                                    created: "2023-04-06T09:20:29.699",
                                    dataElement: "X3Mny2GiXh2",
                                    value: "CPHL",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-06T09:19:22.654",
                                    created: "2023-04-06T09:19:22.654",
                                    dataElement: "YpGySVvEcuI",
                                    value: "Jinja Nile Hotel",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-06T06:15:38.131",
                                    created: "2023-04-06T06:15:38.131",
                                    dataElement: "s3eoonJ8OJb",
                                    value: "2023-04-06",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-06T09:19:31.966",
                                    created: "2023-04-06T09:19:31.966",
                                    dataElement: "oqhHGBCNJGd",
                                    value: "12:19",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-06T09:19:43.779",
                                    created: "2023-04-06T09:19:43.779",
                                    dataElement: "PaCUNfho8eD",
                                    value: "Blood",
                                    providedElsewhere: false,
                                },
                            ],
                            notes: [],
                            relationships: [],
                        },
                        {
                            storedBy: "Charles.Olupot",
                            dueDate: "2023-04-06T06:17:13.094",
                            program: "o6TN8Sr45CZ",
                            event: "AvLxgqAFj6W",
                            programStage: "BdEhhLbNdmy",
                            orgUnit: "a4gTh6i5VdH",
                            trackedEntityInstance: "VgzcxlyMAOR",
                            enrollment: "ma8b1wyyDyv",
                            enrollmentStatus: "ACTIVE",
                            status: "ACTIVE",
                            orgUnitName: "1 Test OU",
                            eventDate: "2023-04-06T00:00:00.000",
                            attributeCategoryOptions: "xYerKDKCefk",
                            lastUpdated: "2023-04-06T06:17:13.095",
                            created: "2023-04-06T06:17:12.501",
                            deleted: false,
                            attributeOptionCombo: "HllvX50cXC0",
                            dataValues: [
                                {
                                    lastUpdated: "2023-04-06T06:17:13.093",
                                    created: "2023-04-06T06:17:13.093",
                                    dataElement: "s3eoonJ8OJb",
                                    value: "2023-04-06",
                                    providedElsewhere: false,
                                },
                            ],
                            notes: [],
                            relationships: [],
                        },
                    ],
                },
            ],
            relationships: [],
            attributes: [
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Action Taken",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "Rx2fEI9zDJ3",
                    value: "SpecimenCollected",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Age (yrs)",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "INTEGER_ZERO_OR_POSITIVE",
                    attribute: "UezutfURtQG",
                    value: "20",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Case notified by:",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "bZGmeF1bpcx",
                    value: "Direct call",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Full name",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "sB1IHYu2xQT",
                    value: "CPX Olupot",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Gender",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "Rq4qM2wKYFL",
                    value: "Male",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Suspected Disease/Condition",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "rpkGPScBEus",
                    value: "COVID19",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Status at notification",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "Fs892x4qy0d",
                    value: "Alive",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Type of Case",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "hUvDUjcFmFB",
                    value: "Human",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "District Case ID",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "HAZ7VQ730yn",
                    value: "CBDS0649101",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "District and Subcounty",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "Za0xkyQDpxA",
                    value: "ABAKO_SC",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Nationality",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "XvETY1aTxuB",
                    value: "BW",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Barcode No ",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "rSKAr1Ho7rI",
                    value: "TESTBAR",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Where sample is collected",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "cRRJ9fsIYYz",
                    value: "POE",
                },
                {
                    lastUpdated: "2023-04-06T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "v3: Type of Person Test",
                    created: "2023-04-06T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "JdQtKTG6Nw6",
                    value: "Truck Driver",
                },
            ],
        },
        {
            created: "2023-04-08T17:15:01.119",
            orgUnit: "a4gTh6i5VdH",
            createdAtClient: "2023-04-08T17:15:01.119",
            trackedEntityInstance: "DiC58WSNtNZ",
            lastUpdated: "2023-04-08T17:15:01.132",
            trackedEntityType: "KWN8FUfvO5G",
            // lastUpdatedAtClient: "2023-04-08T17:15:01.119",
            inactive: false,
            deleted: false,
            featureType: "NONE",
            programOwners: [
                {
                    ownerOrgUnit: "a4gTh6i5VdH",
                    program: "o6TN8Sr45CZ",
                    trackedEntityInstance: "DiC58WSNtNZ",
                },
            ],
            enrollments: [
                {
                    storedBy: "Charles.Olupot",
                    created: "2023-04-08T17:15:01.865",
                    orgUnit: "a4gTh6i5VdH",
                    createdAtClient: "2023-04-08T17:15:01.874",
                    program: "o6TN8Sr45CZ",
                    trackedEntityInstance: "DiC58WSNtNZ",
                    enrollment: "p9N0qNknADM",
                    lastUpdated: "2023-04-08T17:15:01.874",
                    trackedEntityType: "KWN8FUfvO5G",
                    // lastUpdatedAtClient: "2023-04-08T17:15:01.874",
                    orgUnitName: "1 Test OU",
                    enrollmentDate: "2023-04-08T00:00:00.000",
                    deleted: false,
                    incidentDate: "2023-04-08T00:00:00.000",
                    status: "ACTIVE",
                    notes: [],
                    relationships: [],
                    attributes: [],
                    events: [
                        {
                            storedBy: "Charles.Olupot",
                            dueDate: "2023-04-08T17:17:16.328",
                            program: "o6TN8Sr45CZ",
                            event: "uHflkTvENNs",
                            programStage: "zKFHLSj6Wd1",
                            orgUnit: "a4gTh6i5VdH",
                            trackedEntityInstance: "DiC58WSNtNZ",
                            enrollment: "p9N0qNknADM",
                            enrollmentStatus: "ACTIVE",
                            status: "ACTIVE",
                            orgUnitName: "1 Test OU",
                            eventDate: "2023-04-08T00:00:00.000",
                            attributeCategoryOptions: "xYerKDKCefk",
                            lastUpdated: "2023-04-08T17:17:16.329",
                            created: "2023-04-08T17:15:29.205",
                            deleted: false,
                            attributeOptionCombo: "HllvX50cXC0",
                            dataValues: [
                                {
                                    lastUpdated: "2023-04-08T17:17:11.810",
                                    created: "2023-04-08T17:17:11.810",
                                    dataElement: "Iwiv0W39Yqq",
                                    value: "PCR",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-08T17:17:16.325",
                                    created: "2023-04-08T17:17:16.325",
                                    dataElement: "GzIo6aEN7Mc",
                                    value: "2023-04-08",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-08T17:15:52.438",
                                    created: "2023-04-08T17:15:52.438",
                                    dataElement: "Jpq7RcEf56x",
                                    value: "1",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-08T17:16:54.694",
                                    created: "2023-04-08T17:16:19.793",
                                    dataElement: "Ju7cS1sUwcF",
                                    value: "L202300_15",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-08T17:15:41.975",
                                    created: "2023-04-08T17:15:41.975",
                                    dataElement: "YpGySVvEcuI",
                                    value: "Arapai HC III",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-08T17:15:29.980",
                                    created: "2023-04-08T17:15:29.980",
                                    dataElement: "s3eoonJ8OJb",
                                    value: "2023-04-08",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-08T17:15:49.069",
                                    created: "2023-04-08T17:15:49.069",
                                    dataElement: "oqhHGBCNJGd",
                                    value: "20:13",
                                    providedElsewhere: false,
                                },
                                {
                                    lastUpdated: "2023-04-08T17:16:09.404",
                                    created: "2023-04-08T17:16:09.404",
                                    dataElement: "PaCUNfho8eD",
                                    value: "Nasopharyngeal Swab",
                                    providedElsewhere: false,
                                },
                            ],
                            notes: [],
                            relationships: [],
                        },
                    ],
                },
            ],
            relationships: [],
            attributes: [
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Action Taken",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "Rx2fEI9zDJ3",
                    value: "SpecimenCollected",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Age (yrs)",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "INTEGER_ZERO_OR_POSITIVE",
                    attribute: "UezutfURtQG",
                    value: "34",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Case notified by:",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "bZGmeF1bpcx",
                    value: "Call Center",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Full name",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "sB1IHYu2xQT",
                    value: "John Doe",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Gender",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "Rq4qM2wKYFL",
                    value: "Male",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Suspected Disease/Condition",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "rpkGPScBEus",
                    value: "COVID19",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Status at notification",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "Fs892x4qy0d",
                    value: "Alive",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Type of Case",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "hUvDUjcFmFB",
                    value: "Human",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Village",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "ttjZl7jvrRj",
                    value: "Awasi",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Parish",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "v24me96F6XA",
                    value: "Awasi",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "District Case ID",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "HAZ7VQ730yn",
                    value: "CBDS0649103",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "District and Subcounty",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "Za0xkyQDpxA",
                    value: "ARAPAI_TC",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Nationality",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "XvETY1aTxuB",
                    value: "UG",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "Where sample is collected",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "cRRJ9fsIYYz",
                    value: "Health Facility",
                },
                {
                    lastUpdated: "2023-04-08T00:00:00.000",
                    storedBy: "Charles.Olupot",
                    displayName: "v3: Type of Person Test",
                    created: "2023-04-08T00:00:00.000",
                    valueType: "TEXT",
                    attribute: "JdQtKTG6Nw6",
                    value: "Health Worker",
                },
            ],
        },
    ],
};
